### ISSUE TITLE
The Best Logging Framework is…

### ISSUE THREAD

**Issue by mwawrzyniiak** [kubawich/DistributedWebApp#17]
https://stackify.com/nlog-vs-log4net-vs-serilog/
analysis and selection of the best logger for our project

**Comment by mwawrzyniiak** [comment]
Proponuję, żebyśmy poszli za sugestią autora artykułu, i używali `Serilog`. Logowanie strukturalne jest na pewno zgodne z naszym podejściem clean ar i clean code.

**Comment by kubawich** [comment]
Picked [Serilog](https://github.com/serilog/serilog) as a default logging solution.

**Comment by mwawrzyniiak** [comment]
structured login selection
